// 生成于 GLM-5V-Turbo
// Auto-scan src/plugins/*.ts and generate src/pluginsGen.ts
//
// Convention: each plugin file exports a {basename}Plugin constant.
//   e.g. core.ts  -> export const corePlugin: PluginDef
//       hexal.ts -> export const hexalPlugin: PluginDef
//
// Excluded files (non-plugin infrastructure):
//   index.ts, registry.ts, pluginsGen.ts

const fs = require('fs')
const path = require('path')

const SCRIPT_DIR = path.resolve(__dirname)
const PLUGINS_DIR = path.join(SCRIPT_DIR, '..', 'src', 'plugins')
const OUTPUT_FILE = path.join(SCRIPT_DIR, '..', 'src', 'pluginsGen.ts')

/** Always place core first in the output list */
const CORE_NAME = 'core'

function main() {
    if (!fs.existsSync(PLUGINS_DIR)) {
        console.error(`[error] Plugins directory not found: ${PLUGINS_DIR}`)
        process.exit(1)
    }

    const files = fs.readdirSync(PLUGINS_DIR).filter((f) => f.endsWith('.ts')).sort()

    if (files.length === 0) {
        console.warn('[warn] No plugin files found')
        return
    }

    // Separate core to keep it first
    const coreIdx = files.indexOf(`${CORE_NAME}.ts`)
    const coreFile = coreIdx >= 0 ? files.splice(coreIdx, 1)[0] : null

    const imports = []
    const entries = []

    if (coreFile) {
        const name = coreFile.replace(/\.ts$/, '')
        imports.push(`import { ${name}Plugin } from './plugins/${name}'`)
        entries.push(`    ${name}Plugin,  // core -- always first`)
    }

    for (const f of files) {
        const name = f.replace(/\.ts$/, '')
        imports.push(`import { ${name}Plugin } from './plugins/${name}'`)
        entries.push(`    ${name}Plugin,`)
    }

    const content = [
        `// Auto-generated by scripts/generate-plugins.js -- do not edit manually`,
        `import { PluginDef } from './types'`,
        ``,
        ...imports,
        ``,
        `/** All registered plugins (auto-scanned from src/plugins/) */`,
        `export const ALL_PLUGINS: PluginDef[] = [`,
        ...entries,
        `]`,
        ``,
    ].join('\n')

    fs.writeFileSync(OUTPUT_FILE, content, 'utf8')
    console.log(`[ok] Generated ${OUTPUT_FILE} (${entries.length} plugins)`)
}

main()
