// Generated by GLM-5V-Turbo
// linkSelf.js - Auto-discover .\w dirs and create links to this extension dir
// Usage: node scripts/linkSelf.js [-a] [-f]

const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

// ─── Args ────────────────────────────────────────────────────
const rawArgs = process.argv.slice(2)
/** Resolve flag from CLI args, then npm config env vars (npm eats unknown flags) */
function hasFlag(flag, npmEnvName) {
    if (rawArgs.includes(flag)) return true
    const val = process.env[`npm_config_${npmEnvName}`]
    return val === 'true' || val === ''
}
const requestElevate = hasFlag('-a', 'all')
const forceDelete = hasFlag('-f', 'force')
/** Args passed to the actual worker (strips -a) */
const args = rawArgs.filter(a => a !== '-a')
/** Optional: redirect all output to a log file (used by UAC elevation) */
const logToFile = args.find(a => a.startsWith('--log-to='))
if (logToFile) {
    const logPath = logToFile.split('=')[1]
    const logFd = fs.openSync(logPath, 'w')
    // Override console to write to file
    const origLog = console.log
    const origErr = console.error
    console.log = (...parts) => {
        fs.writeSync(logFd, parts.join(' ') + '\n')
        origLog(...parts)
    }
    console.error = (...parts) => {
        fs.writeSync(logFd, '[ERR] ' + parts.join(' ') + '\n')
        origErr(...parts)
    }
}

// ─── UAC self-elevation (-a) ─────────────────────────────────
if (requestElevate) {
    const nodeExe = process.execPath
    const scriptPath = process.argv[1]
    const outFile = path.join(process.env.TEMP || process.env.tmp || '.', `linkSelf_${Date.now()}.log`)
    // Reconstruct flags from resolved values (rawArgs may be empty due to npm)
    const childFlags = []
    if (forceDelete) childFlags.push('-f')
    if (logToFile) childFlags.push(logToFile)
    const argList = [scriptPath, ...childFlags, `--log-to=${outFile}`].map(a => `'${a.replace(/'/g, "''")}'`).join(',')
    try {
        execSync(
            `powershell -Command "Start-Process '${nodeExe.replace(/'/g, "''")}' -ArgumentList ${argList} -Verb RunAs -Wait -WindowStyle Hidden"`,
            { stdio: 'pipe' },
        )
    } catch {
        console.error('[error] Elevation failed or was cancelled.')
        process.exit(1)
    }
    // Print captured output from elevated child
    if (fs.existsSync(outFile)) {
        process.stdout.write(fs.readFileSync(outFile, 'utf8'))
        fs.unlinkSync(outFile)
    }
    process.exit(0)
}

// ─── Paths ───────────────────────────────────────────────────
const SCRIPT_DIR = path.resolve(__dirname)
const EXT_DIR = path.resolve(SCRIPT_DIR, '..') // hexParse_highlight
/** Search roots for .\w subdirectories */
const SEARCH_ROOTS = [process.env.USERPROFILE].filter(Boolean)
const EXT_NAME = path.basename(EXT_DIR)

// ─── VSCode-compatible editor detection ───────────────────────

function isVscodeCompatibleEditor(dirPath) {
    try {
        if (!fs.statSync(dirPath).isDirectory()) return false
        const entries = fs.readdirSync(dirPath)
        const indicators = ['extensions', 'User', 'globalStorage', 'workspaceStorage', 'logs']
        return indicators.some(ind => entries.includes(ind))
    } catch {
        return false
    }
}

// ─── Find .\w directories ─────────────────────────────────────

function findDotWordDirs(root) {
    const result = []
    try {
        const entries = fs.readdirSync(root, { withFileTypes: true })
        for (const entry of entries) {
            if (entry.isDirectory() && /^\.\w/.test(entry.name)) {
                result.push(path.join(root, entry.name))
            }
        }
    } catch (err) {
        console.error(`[error] Cannot read directory ${root}: ${err.message}`)
    }
    return result
}

// ─── Create link: junction first, fallback to symlink ─────────

/**
 * @param {string} linkPath
 * @param {string} targetPath
 * @returns {{ ok: boolean, message: string }}
 */
function createLink(linkPath, targetPath) {
    // Handle existing target
    if (fs.existsSync(linkPath)) {
        if (forceDelete) {
            try {
                fs.rmSync(linkPath, { recursive: true, force: true })
                console.log(`[info] Removed existing: ${linkPath}`)
            } catch (err) {
                return { ok: false, message: `[fail] Cannot remove ${linkPath}: ${err.message}` }
            }
        } else {
            return { ok: false, message: `[skip] Target already exists (use -f to overwrite): ${linkPath}` }
        }
    }

    // Ensure parent exists
    const parentDir = path.dirname(linkPath)
    if (!fs.existsSync(parentDir)) {
        try {
            fs.mkdirSync(parentDir, { recursive: true })
        } catch (err) {
            return { ok: false, message: `[fail] Cannot create parent dir ${parentDir}: ${err.message}` }
        }
    }

    // Attempt 1: junction (/J)
    try {
        execSync(`mklink /J "${linkPath}" "${targetPath}"`, { stdio: 'pipe', shell: true })
        return { ok: true, message: `[ok] Junction: ${linkPath}` }
    } catch (junctionErr) {
        const jStderr = junctionErr.stderr ? junctionErr.stderr.toString().trim() : ''
        // Attempt 2: directory symlink (/D)
        try {
            execSync(`mklink /D "${linkPath}" "${targetPath}"`, { stdio: 'pipe', shell: true })
            return {
                ok: true,
                message: `[ok] Symlink:  ${linkPath}  (junction failed: ${jStderr || junctionErr.message})`,
            }
        } catch (symlinkErr) {
            const sStderr = symlinkErr.stderr ? symlinkErr.stderr.toString().trim() : symlinkErr.message
            return {
                ok: false,
                message: `[fail] Both methods failed for ${linkPath}:\n  junction: ${jStderr || junctionErr.message}\n  symlink:  ${sStderr}`,
            }
        }
    }
}

// ─── Main ────────────────────────────────────────────────────

console.log(`=== linkSelf ===`)
console.log(`Source: ${EXT_DIR}`)
console.log(`Options: forceDelete=${forceDelete}`)
console.log('')

// 1. Collect & deduplicate .\w dirs from all search roots
const dotDirs = []
for (const root of SEARCH_ROOTS) {
    dotDirs.push(...findDotWordDirs(root))
}
const seen = new Set()
const uniqueDotDirs = dotDirs.filter(d => {
    if (seen.has(d)) return false
    seen.add(d)
    return true
})

if (uniqueDotDirs.length === 0) {
    console.log('[done] No .\\w directories found.')
    process.exit(0)
}

// 2. Filter editor dirs that contain an 'extensions' subdir
let successCount = 0
let failCount = 0

for (const dotDir of uniqueDotDirs) {
    if (!isVscodeCompatibleEditor(dotDir)) continue

    const extSubdir = path.join(dotDir, 'extensions')
    if (!fs.existsSync(extSubdir)) continue

    const linkPath = path.join(extSubdir, EXT_NAME)
    const result = createLink(linkPath, EXT_DIR)
    console.log(result.message)
    if (result.ok) successCount++
    else failCount++
}

console.log('')
console.log(`=== Result: ${successCount} succeeded, ${failCount} failed ===`)
if (failCount > 0 && successCount === 0) process.exit(1)
