// Auto-generated by scripts/generate-plugins.js -- do not edit manually
import { PluginDef } from './types'

import { corePlugin } from './plugins/core'
import { ephemeraPlugin } from './plugins/ephemera'
import { hexArsLinkerPlugin } from './plugins/hexArsLinker'
import { hexFlowPlugin } from './plugins/hexFlow'
import { hexPosePlugin } from './plugins/hexPose'
import { hexalPlugin } from './plugins/hexal'
import { hexcellularPlugin } from './plugins/hexcellular'
import { moreIotasPlugin } from './plugins/moreIotas'
import { oneironautPlugin } from './plugins/oneironaut'

/** All registered plugins (auto-scanned from src/plugins/) */
export const ALL_PLUGINS: PluginDef[] = [
    corePlugin,  // core -- always first
    ephemeraPlugin,
    hexArsLinkerPlugin,
    hexFlowPlugin,
    hexPosePlugin,
    hexalPlugin,
    hexcellularPlugin,
    moreIotasPlugin,
    oneironautPlugin,
]
